### ISSUE TITLE
ouch

### ISSUE THREAD

**Issue by btplayzxgit** [EaglerStorage/Eaglercraft-1.5.2#2]
i didnt skid anything and i have literal proof, look on the klockcraft page. if you don't believe me then listen to this: peytonplayz forgot one cute little detail, when you fork something it shows who is the original owner of the repo pls add me back to this project (i did make that DMCA notice message that you copied and i did think of a better name >:( )

**Comment by Coll147** [comment]
Ok okay I'll make my own letter
